### ISSUE TITLE
Error: Cannot find module './gather.ts'

### ISSUE THREAD

**Issue by WiseKai** [sourlodine/Solana-Raydium-Volume-Bot#3]
Error: Cannot find module './gather.ts'
Require stack:
- C:\Users\BGL\Solana-Raydium-Volume-Bot\imaginaryUncacheableRequireResolveScript
    at Function._resolveFilename (node:internal/modules/cjs/loader:1239:15)
    at Function.resolve (node:internal/modules/helpers:146:19)
    at requireResolveNonCached (C:\Users\BGL\Solana-Raydium-Volume-Bot\node_modules\ts-node\dist\bin.js:549:16)
    at getProjectSearchDir (C:\Users\BGL\Solana-Raydium-Volume-Bot\node_modules\ts-node\dist\bin.js:519:40)
    at phase3 (C:\Users\BGL\Solana-Raydium-Volume-Bot\node_modules\ts-node\dist\bin.js:267:27)
    at bootstrap (C:\Users\BGL\Solana-Raydium-Volume-Bot\node_modules\ts-node\dist\bin.js:47:30)
    at main (C:\Users\BGL\Solana-Raydium-Volume-Bot\node_modules\ts-node\dist\bin.js:33:12)
    at Object.<anonymous> (C:\Users\BGL\Solana-Raydium-Volume-Bot\node_modules\ts-node\dist\bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\BGL\\Solana-Raydium-Volume-Bot\\imaginaryUncacheableRequireResolveScript'
  ]
}

Cant gather SOL. Cant do anything, took all my SOL into random wallets.

**Comment by Kellytimmins** [comment]
Hello @WiseKai 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
